server:
  port: 8080 

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 🔥 PRO-TIP: Isko ab false kar dijiye kyunki aapne custom routes bana liye hain
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" 
            allowedMethods: "*"
            allowedHeaders: "*"

# Swagger Aggregation Config
springdoc:
  swagger-ui:
    path: /docs    
    urls:
      - name: Recruiter Auth Service
        url: /recruiter-service/v3/api-docs
      - name: Job & AI Service
        url: /job-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,gateway,info"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
