server:
  port: 8080 

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # Route 1: Authentication Endpoints
        - id: recruiter-service-auth
          uri: lb://RECRUITER-SERVICE 
          predicates:
            - Path=/api/v1/auth/**

        # Route 2: Recruiter Data Endpoints
        - id: recruiter-service-data
          uri: lb://RECRUITER-SERVICE 
          predicates:
            - Path=/api/v1/recruiters/**
            
        - id: job-service
          uri: lb://JOB-SERVICE 
          predicates:
            - Path=/api/v1/jobs/**     

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
