server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/job_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: "gemini-2.5-flash"
            temperature: 0.2

  rabbitmq:
    host: rabbitmq-broker
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

cloud:
  aws:
    region: eu-north-1
    s3:
      bucket-name: "arijit-recruiter-saas-2026"
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
